version: '2.1'

services:
  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: workshop
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"

  workshop:
    container_name: node-workshop
    build: ./
    hostname: node-workshop
    volumes:
      - ./app:/var/www/workshop/app
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data: