version: '3'

services:
  api:
    container_name: node-workshop-2
    hostname: node-workshop-2
    build: ./
    volumes:
      - ./src:/var/www/lingviny-api/src
    ports:
      - "3000:3000"
    env_file: "./docker/environments"
